### ISSUE TITLE
Add Hugeicons

### ISSUE THREAD

**Issue by zafercuz** [iconify/icon-sets#109]
Hi,

Is it possible to add [Hugeicons](https://hugeicons.com/), of course only the free icons offered by them

- Repo: They don't have a repo but they do have for a React repo however their icons are in a React file instead of just svg but I'll just link it if it helps in any way
    - https://github.com/hugeicons/hugeicons-react/tree/main/icons
- Website: https://hugeicons.com/
- Free icons: https://hugeicons.com/icons?style=Stroke&type=Rounded
- License: Based on their React package it is `CC0-1.0`
    - https://www.npmjs.com/package/hugeicons-react
    - More info for their license agreement: https://hugeicons.com/license-agreement
- Figma: 
    - https://www.figma.com/community/plugin/1209922740177393208/hugeicons-pro-icon-library
    - https://www.figma.com/file/GI8zrgL8MqbsWlQEzznX0N/Hugeicons-Pro---Icon-Library?type=design&node-id=18027-185&mode=design&t=87hYr99hJlnVK7Tn-0

**Comment by cyberalien** [comment]
Using React package as source won't work. It needs to be SVG.

**Comment by andreas-straub** [comment]
There is a SVG for each file available. For example here: https://cdn.hugeicons.com/icons/1st-bracket-square-stroke-rounded.svg

**Comment by cyberalien** [comment]
That's not usable because it is not on any kind of version control. There is no way to check if icons have been updated, except for retrieving each icon.

I'm also not keen on adding it in current state because there is no clear open source license for free icons. It is not mentioned anywhere on website, only in React repository.

If author of icon set publishes SVGs on GitHub or any other Git repository, it can be imported. Otherwise I won't be adding it.

**Comment by andreas-straub** [comment]
@cyberalien OK, thx for clarification
