### ISSUE TITLE
How do I use weights / outlined variant with Material Symbols

### ISSUE THREAD

**Issue by matthew-dean** [iconify/icon-sets#114]
Material Symbols distributes dozens (or more?) font variants of its icons, presumably all with different glyphs. Notably, it distributes different weights and variants like outlined or filled. (These are not simple filling of a shape or not, AFAIK.)

Iconify seems to only distribute 1 set of all of Material Symbols variants.

You can see an example of this in the [Material Symbols SVG packages](https://www.npmjs.com/package/@material-symbols/svg-400), which have different packages for each weight, but then _separately_ have exported SVGs / components per style.

Are you planning to support the full set of Material Symbols icons?

**Comment by cyberalien** [comment]
I have no plans to do that.

Without source files and way to convert them to variations, all variations of same icon must be treated as separate icons. There are 12.5k icons for just one variation, with all variations that's hundreds of thousands of icons.

Adding all those variations would:
- Flood search results with massive amount of almost identical icons. Though it can be solved by filtering variations, but it would require extra development time.
- API would have to host all those icons in order to serve data to icon component.
- Website would have to be changed to treat variations differently, so that's more work.

The biggest issue by far is API. Hosting all those icons at Iconify API would require at least 3 times higher memory usage than servers have now, which would drastically increase costs. GitHub sponsors don't even cover current server costs, so that's not going to happen.

The only way I would add variations is if source files were available, then it would be just one icon and simple script to convert it to required variation.
