### ISSUE TITLE
Add Catppuccin VS Code Icons

### ISSUE THREAD

**Issue by antfu** [iconify/icon-sets#124]
https://github.com/catppuccin/vscode-icons

This icon set is very well-designed, beautiful, and consistently styled. It would be great to be able to use it in the Iconify ecosystem.

![](https://github.com/catppuccin/vscode-icons/raw/main/assets/macchiato.webp)

Catppuccin contains of 4 different color themes, same for the icons. I am not sure if we should include all 4 variants, or should we pick one to include.

/cc @prazdevs

**Comment by cyberalien** [comment]
I think including just one set is enough. Icons are identical, the only difference is slightly different palette.

With addition of `customise` option to components, changing colors will be very simple. Need to add similar way to customse icons in UnoCSS and Unplugin Icons and users will be able to change palette themselves.

**Comment by antfu** [comment]
Yeah I agree. I would vote to have the Macchiato variant: https://github.com/catppuccin/vscode-icons/tree/main/icons/macchiato, as it seems to have slightly better contrast. For the light mode I guess users could also apply CSS filter like `invert(1) hue-rotate(180)`

**Comment by prazdevs** [comment]
👋 Hi, I'd be pleased to see the icons in Iconify.
I need to read about how to integrate the icons into the project, and the contributing guidelines and such.

I'm not really familiar with themed icons in Iconify. It could make sense to not include all flavours, unsure how icons would look with CSS filter color change (not sure about the readability of all icons)

**Comment by cyberalien** [comment]
Awesome!

> I'm not really familiar with themed icons in Iconify. It could make sense to not include all flavours, unsure how icons would look with CSS filter color change (not sure about the readability of all icons)

Icons are just icons. Iconify makes them easy to use by importing icons from various sources, validating / cleaning up and making icon data available in easy to use format. Various components insert those icons as SVGs to documents (raw SVG or wrapped in web component) or stylesheets (background or mask image).

Icons with hardcoded colors are kept as is, so choice of colors is important because it requires additional steps (which is too much for some users) to change colors.

Do you think it would be better to import one of themes now, such as `Macchiato` variant or later when icons are isolated?

**Comment by cyberalien** [comment]
Added: https://icon-sets.iconify.design/catppuccin/?category=Programming

Also created special "Programming" category for development related icon sets and moved other similar icon sets to it.
