### ISSUE TITLE
Add Kubernetes Component Icons

### ISSUE THREAD

**Issue by HarryGogonis** [iconify/icon-sets#128]
https://github.com/kubernetes/community/tree/master/icons

These are useful for Kubernetes architecture diagrams
License: Apache-2.0 or CC-BY-4.0

**Comment by cyberalien** [comment]
Sorry, no.

That icon set is not usable for several reasons:
1. Icons are too large, not usable at small resolutions. Only icons that are usable at small sizes such as 24x24 are accepted.
2. Many icons contain text elements. Icons that contain text are not allowed because it does not render consistently in various browsers and operating systems.
