### ISSUE TITLE
Artifacts in Noto Emoji's coin emoji

### ISSUE THREAD

**Issue by marwinburesch** [iconify/icon-sets#39]
Hi there,

our team found some artifacts in the [`noto:coin`](https://icon-sets.iconify.design/noto/coin/) emoji. The stars seem to have some incorrect coordinates for some of their points. This might have been introduced with [this commit](https://github.com/iconify/icon-sets/commit/4c114793fb31d1834c3b73e87da4dd80b41616a3) since we're relatively sure, that the coin looked just fine about a month ago.

I would love to open a PR and fix this, but there seems to be a significant difference between [Google's svg code](https://github.com/googlefonts/noto-emoji/blob/main/svg/emoji_u1fa99.svg) and your JSON. As I understand I'd need to use the [Iconify Tools](https://github.com/iconify/tools) to generate correct JSON, however that is also a lot of overhead for me.

This is taken from current version of iconify-sets 
![image](https://user-images.githubusercontent.com/48555130/156389065-dc75ecf9-88a2-4813-95cb-35a3b1c0db99.png)

This is the current version of googlefonts
![image](https://user-images.githubusercontent.com/48555130/156389203-17af7e00-aa35-48ff-af8a-f30413aff210.png)

Please let me know what you think and if this can be fixed in the near future. 

Cheers guys 👋

**Comment by cyberalien** [comment]
Thanks a lot for report. That icon is indeed bugged

**Comment by cyberalien** [comment]
Found and fixed bug that was causing it. Thank you very much for report!

Currently script is updating all packages, it might take up to few hours for fix to appear on API and NPM packages.

Bug affected about 300 icons, in few others I've checked changes are so small that without knowing what to look for bug is not visible. It was caused by error in handling whitespace, which resulted in parts of path being joined incorrectly when path is split over multiple lines.
