### ISSUE TITLE
Add other versions of iconpark icons

### ISSUE THREAD

**Issue by ZvonimirSun** [iconify/icon-sets#44]
I find iconify now has an `icon-park` for `multi-color` theme, and an `icon-park-outline` for `line` theme. Can you please add the `fill` theme and `two-tone` theme of the iconpark icon set?

https://iconpark.oceanengine.com/official
https://github.com/bytedance/iconpark

**Comment by cyberalien** [comment]
Those themes are not usable.

Fill theme uses black color for shapes and white color for bits that are supposed to be transparent. Black can be changed to currentColor to allow changing color, but white cannot be changed. That means icons will work only on white background, so it is not usable.

TwoTone theme is not usable because of how icons are designed. If it is used as black/blue, it is not any different from default, so it is pointless. If it is used as true two tone icon, which means instead of black using currentColor and instead of blue using semi-transparent color, it is still not usable because icons are not designed with transparency in mind - many shapes overlap each other, making icons unusable with transparent color. So theme is not usable either.

**Comment by cyberalien** [comment]
Added.

After more tests, I found a solution. Icon palette issues can be fixed by using masks and I figured out how to automate it.

Solid icons do look similar to official website, except that white areas are not white, but transparent, so icons work with all color schemes: https://icon-sets.iconify.design/icon-park-solid/

Two tone icons use currentColor for solid areas and currentColor with 33% opacity for semi-transparent parts: https://icon-sets.iconify.design/icon-park-twotone/
