### ISSUE TITLE
Some icons from Material Symbols are missing 

### ISSUE THREAD

**Issue by clemyan** [iconify/icon-sets#45]
For example, the [`cloud_upload`](https://fonts.google.com/icons?icon.query=cloud_upload&icon.style=Outlined) icon is missing.

Could you check your update script to see if it is grabbing all icons?

**Comment by cyberalien** [comment]
That icon is identical to `backup`: https://icon-sets.iconify.design/material-symbols/backup-outline/

A lot of icons in Material Symbols are duplicates of other icons. Update script detects those duplicates and creates aliases, so icon can be used by either name.

**Comment by cyberalien** [comment]
If you don't mind, I'll keep this issue open for a while. Icons filter on website needs fixing.

Currently if you look for `cloud-upload` (all icons in Iconify use `-` instead of underscore), it shows only solid version `backup`, but not `backup-outline` that `cloud-upload-outline` redirects to. That's clearly a bug in filter function.

**Comment by cyberalien** [comment]
Fixed in upcoming version of Icon Finder.
