### ISSUE TITLE
Request: add fluent-emoji from Microsoft

### ISSUE THREAD

**Issue by kissu** [iconify/icon-sets#52]
It's brand new and a bit special but those are finally open-sourced and quite super cute. 👌🏻
https://github.com/microsoft/fluentui-emoji

**Comment by cyberalien** [comment]
So I've fixed errors in my validator script and converted icon set.

It is somewhat usable. Somewhat.

In other emoji sets average icon size is about 2kb per icon, in simple icon sets such as Material Icons its below 500 bytes per icon.

In Fluent Emoji average icon size is 30463 bytes! When showing 52 icons per page, page freezes for several seconds in Chrome. For each icon hover, it freezes again for a second. I've never seen such massive rendering lag. Issue is caused by huge amount of filters used in each icon, which takes massive amount of CPU time to render.

I'll publish icon set, but for now it is unusable for websites. That's very unfortunate because icons are very cool.

**Comment by cyberalien** [comment]
Added! https://icon-sets.iconify.design/fluent-emoji/

I'll add flat and high contrast variations later this weekend.

**Comment by kissu** [comment]
Damn amazing! Thank you very much. ♥

**Comment by cyberalien** [comment]
Added `Flat` and `High Contrast` versions too.

Unlike default set, these variations don't contain huge number of gradients and filters, so files are small. For flat average size is 2.8kb per icon, for high contrast its 1.7kb... compared to 30kb for default.

High contrast is especially awesome to have because it is basically a good monotone icon set, but for emojis instead of general UI icons. Before this set, the only other monotone emoji set was outdated Emoji One version 1 set.

**Comment by cyberalien** [comment]
Website has finally rebuilt.

Icon sets are available here:
- http://icon-sets.iconify.design/fluent-emoji-flat/
- http://icon-sets.iconify.design/fluent-emoji-high-contrast/
