### ISSUE TITLE
add Coco Icons

### ISSUE THREAD

**Issue by ali110309** [iconify/icon-sets#64]
hi 
pls add this free icon pack to iconify
links: 
https://www.svgrepo.com/collection/coco-line-icons/
https://www.svgrepo.com/collection/coco-bold-icons/
https://www.svgrepo.com/collection/coco-two-color-icons/
https://www.svgrepo.com/collection/coco-duotone-icons/
tanx

**Comment by cyberalien** [comment]
It cannot be added because:
- No clear license or author. Only open source icon sets are added.
- Icon sets are automatically updated from its source, which can be either git repository, NPM package or Figma file (other options can be added too). Those sets are only available at some website, making it impossible to automatically maintain it.

Any icons at that or similar website are not usable. Those are just dumps of icons, no mention of author or attribution, no mention of license, no way to icons other than one by one.
