### ISSUE TITLE
Missing some OpenSource IconSets

### ISSUE THREAD

**Issue by iuridiniz** [iconify/icon-sets#66]
Hi, everyone

I've found these iconsets are opensource and not included in Iconify:
- [Circum](https://circumicons.com/) - [MPL 2.0](https://github.com/Klarr-Agency/Circum-Icons/blob/main/LICENSE)
- [DevIcons](https://devicon.dev/) - [MIT](https://github.com/devicons/devicon/blob/master/LICENSE)
- [GovIcons](http://govicons.io/) -  [SIL Open Font License (OFL)](https://github.com/540co/govicons/blob/develop/LICENSE.md)
- [Linearicons](https://linearicons.com/free) - [CC BY-SA 4.0](https://linearicons.com/free#about)
- [OpenWeb Icons](https://pfefferle.dev/openwebicons/) - [SIL Open Font License (OFL) - I think...](https://pfefferle.dev/openwebicons/#license)
- [Themify Icons](https://themify.me/themify-icons) - SIL Open Font License (OFL) - (I find the license inside readme.txt on downloaded [themify-icons.font.zip](https://themify.me/download/7/))

If they could be included, I will try to make some PR's to include each one (if easy)

**Comment by cyberalien** [comment]
Thanks.

Added Circus, which is a very well designed icon set.

Not sure about Devicon. It seems like just a collection of logos scaled down to 128x128. Some have palette, some are monotone. There are better sets of logos that are cleaned up and maintained. Though will check them properly later.

GovIcons haven't been maintained for 5 years and icons are badly designed. They have seemingly random padding on sides with icon just placed in middle. Probably usable as font, but as SVGs it is very bad.

Icon sets that aren't on GitHub or NPM or anywhere else that would allow automatic maintenance cannot be added.

**Comment by Snailedlt** [comment]
Hi there, maintainer of devicons here, and we would love it if our icons were added to iconify!

Maybe I can help clear up some things?

1. All of our icons are vector icons, so scale isn't an issue. The reason the viewbox is `0 0 128 128` is just so that they have the same size in browsers, but this size can be edited however you see fit without sacrifising quality.
2. deviconicons are centered with minimal whitespace ensuring easy alignment
3. devicon icons have transparant backgrounds
4. devicon icons exists as both SVG's and fonts
5. We have a few different [SVG-Versions](https://github.com/devicons/devicon/wiki/SVG-Versions) that need to follow different standards. I could tell you more about them, but it's probably easier to just click on the wiki link :)

If you have any more questions, please do let me know!

**Comment by cyberalien** [comment]
Hi and welcome!

My main concern regarding devicons is palette.

Icon sets are clearly split by palette: in an icon set all icons have either:
- hardcoded colors, so icons cannot be customised.
- use `currentColor`, so icons follow text color set by user.

This makes it easy for users to choose icons that fit their website. 

In devicons some icons don't have palette, like this one: https://github.com/devicons/devicon/blob/master/icons/aarch64/aarch64-plain.svg, other icons do, like this one: https://github.com/devicons/devicon/blob/master/icons/aftereffects/aftereffects-plain.svg

Would I be correct to assume that `plain` icons are supposed to be monotone? What's the logic of palette in `original` icons?



Another concern is maintenance. I see that repository has lots of issues, mostly icon requests, but last time it was maintained about half a year ago. There are also many pull requests. Is repository dead?

**Comment by Snailedlt** [comment]
Hi, thanks for the info!

Yes, `plain` icons are supposed to be monotone, and contain only a single path.
`original` icons are as close to the original logo as possible, sometimes with slight changes to the svg structure.

The project is very much alive still, however we have recently changed maintainers. 3 active maintainers recently left, and 3 new ones joined (me included). Therefore there haven't been any new releases in a while, both because the previous maintainers were pretty inactive near the end, and because us new maintainers have had to get the new rights. 
However if you look at the [recently merged PRs](https://github.com/devicons/devicon/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc) and the [diff between the master and develop branches](https://github.com/devicons/devicon/compare/master...develop), you can see that a lot of new icons and features have been added since the last release.

All that said, we hope to make a new release  sometime in december this year, and much more frequently after that.

**Comment by cyberalien** [comment]
Excellent news.

Due to palette limitations in Iconify, it can be added as 2 icon sets: one for `plain` icons without palette, one for `original` icons with palette. Would you be ok with that?

Each icon set has a prefix, like `mdi` for Material Design Icons. I suggest to use `devicon` for plain icons, `devicon-original` for original icons. What do you prefer?

**Comment by Snailedlt** [comment]
@cyberalien Yes that sounds good, but could we also add the other versions?

These are all of our icon versions:
monocolored: `line`, `plain`, `plain-wordmark`, `line-wordmark`
not monocolored: `original`, `original-wordmark`

More info about the icon versions can be found here: https://github.com/devicons/devicon/wiki/SVG-Versions
https://github.com/devicons/devicon/wiki/SVG-Standards

`devicon` sounds like a good prefix 💯

**Comment by cyberalien** [comment]
Oh, there is `line`? I haven't seen one yet, but now I found one. Sure.

So, options:
- `devicon` prefix for plain icons and line icons (monotone icons).
- `devicon-original` prefix for original icons (icons with palette).

or:
- `devicon` prefix for plain icons.
- `devicon-line` prefix for line icons.
- `devicon-original` prefix for original icons.

All of them include `wordmark` variations. It took a while to find a `line` icon, so it doesn't look like there are many of them, so maybe they don't need a separate prefix?

Examples:
- `aarch64/aarch64-plain.svg` would end up with name `devicon:aarch64`
- `css3/css3-plain-wordmark.svg` would end up with name `devicon:css3`
- `css3/css3-original-wordmark.svg` would end up with name `devicon-original:css3-wordmark`
- `tensorflow/tensorflow-line-wordmark.svg` would end up with name `devicon:tensorflow-line-wordmark` or `devicon-line:tensorflow-wordmark`

Or anything else?

**Comment by Snailedlt** [comment]
I would personally prefer the following prefixes:
- `devicon-plain`
- `devicon-line`
- `devicon-original`
All of them including wordmark versions

> It took a while to find a line icon, so it doesn't look like there are many of them

Yeah, there are way fewer than the other versions. In the [develop](https://github.com/devicons/devicon/tree/develop) branch there are currently 56 icons that are either `line` or `line-wordmark` version, and we are moving more towards higher quality PRs lately, so more and more are coming

**Comment by cyberalien** [comment]
Sure

**Comment by Snailedlt** [comment]
Let me know if there's anything more I can help with :)

**Comment by cyberalien** [comment]
One more question: do you prefer icon set names to be like `Devicon Plain` or `Devicon (Plain)` or something else?

**Comment by cyberalien** [comment]
So I've tried adding it.

All icons in Iconify go through validation process to make sure they don't include anything that should not be there, such as:
- Raster images. They have no place being in vector icons.
- Text. It renders differently on different browsers and operating system, making icon look different for different users.
- Monotone icons should not have multiple colors (automatically fixed).
- Icons with hardcoded palette should not rely on system default fill (automatically fixed).
- No bad code, such as referencing masks or clip paths that do not exist.

Result is bunch of issues I've opened at repository.

In addition to that, many monotone icons have multiple colors. Usually would not be an issue, replacing them with `currentColor` usually works, but combined with terrible code in icons, it cannot be auto-fixed because I just don't trust that code. Checking each icon is not an option, there are too many of them throwing that error.

Then there is design issue. Just look at this example: https://github.com/devicons/devicon/blob/master/icons/towergit/towergit-plain.svg then compare it to this: https://github.com/devicons/devicon/blob/master/icons/aarch64/aarch64-plain.svg

Grid placement doesn't make any sense.

Sorry, but that icon set cannot be added yet, until bugs have been fixed and icons redesigned. Quality of icons is just too low in both design and code.

I'll keep this issue open for now, will revisit when issue are fixed and hoping to add it later.

**Comment by iuridiniz** [comment]
> Icon sets that aren't on GitHub or NPM or anywhere else that would allow automatic maintenance cannot be added.

OpenWebIcons are in github as well:
https://github.com/pfefferle/openwebicons

**Comment by cyberalien** [comment]
> > Icon sets that aren't on GitHub or NPM or anywhere else that would allow automatic maintenance cannot be added.
> 
> OpenWebIcons are in github as well: https://github.com/pfefferle/openwebicons

Yes, but it is very bad. Just look at any icon: https://github.com/pfefferle/openwebicons/blob/master/svg/3deffects.svg

It was designed to work only as icon font.

**Comment by Snailedlt** [comment]
@cyberalien Thank you for all the details. I agree the code and design quality is not up to the standard needed. We'll work towards getting it fixed, and I'll report back to you once it's all fixed

Thank you a lot for making the issues in our repo as well, that will make it much faster to fix, much appreciated!

**Comment by Snailedlt** [comment]
Should we follow up devicons in this issue or https://github.com/iconify/iconify/issues/184 ?

**Comment by iuridiniz** [comment]
Linking here issues created by @cyberalien
- devicons/devicon#1517
- devicons/devicon#1518
- devicons/devicon#1519
- devicons/devicon#1520
- devicons/devicon#1521
- devicons/devicon#1522
- devicons/devicon#1523
