### ISSUE TITLE
Add Atlas icons set

### ISSUE THREAD

**Issue by Sevichecc** [iconify/icon-sets#77]
Icon Set: Altas
GitHub Repository: [Vectopus/Atlas-icons-font](https://github.com/Vectopus/Atlas-icons-font)
License: MIT

Open source [icons library](http://atlasicons.vectopus.com/), Icons available in SVG format, Font, Figma, Adobe XD and Iconjar Libraries.

**Comment by cyberalien** [comment]
> Icons available in SVG format

I don't see SVG files. Where did you see it?

**Comment by Sevichecc** [comment]
SVG files are nested in the fonts folder: 
<img width="290" alt="image" src="https://user-images.githubusercontent.com/91365763/230705796-e2a4e879-4128-4505-a015-58ea3d0e71e1.png">

but you can also download them as packages from their website: https://atlasicons.vectopus.com/
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/91365763/230705835-7e69440d-3fc8-4799-a86b-6a6aecbf34df.png">

**Comment by cyberalien** [comment]
Those are fonts in SVG format, not icons.

**Comment by Sevichecc** [comment]
> Those are fonts in SVG format, not icons.

You're right, the correct way to download SVG icons might be to download them from the website.
<img width="518" alt="image" src="https://user-images.githubusercontent.com/91365763/230706657-23c89e44-1dbf-474f-b09c-f8c88bb42e24.png">

**Comment by cyberalien** [comment]
Sorry, that's not going to work.

Icon sets are maintained automatically, so icons must be available as either Git repository, NPM package or Figma file.

Downloading icons from website is not an option.

Additionally, I did download that pack to see code, icon code is very bad. Icons seem to have random viewBox, like `viewBox="0 0 22.91 19.09"`, not aligned to any grid. It's a badly designed icon set. It probably works fine as font because fonts are all crap anyway (blurry, badly aligned), but as SVG quality is very low.

**Comment by Sevichecc** [comment]
Oh, I was overthinking it at first, thanks for your patience in replying
