### ISSUE TITLE
Add Homelab SVG Assets

### ISSUE THREAD

**Issue by jwr12135** [iconify/icon-sets#78]
[github.com/loganmarchione/homelab-svg-assets](https://github.com/loganmarchione/homelab-svg-assets)
It would be really useful to have this set as it adds many icons for homelab-related software and brands, the majority of which don't already have an icon from Iconify.

All SVG files are 48x48 and are located in the [assets](https://github.com/loganmarchione/homelab-svg-assets/tree/main/assets) directory.
The prefix could be shortened down to `homelab`.
I also made sure to double-check check this wasn't already in iconify  :+1:.

**Comment by cyberalien** [comment]
Tried adding it, but that set has too many issues:

1. Some icons use text, which is unacceptable.
2. Some icons do have fonts embedded.
3. Huge amount of bad code in icons, though it is not critical because parser does fix it, it shows that icons were exported without care for quality.
4. Most icons have colors, but some icons have all colors stripped. Very inconsistent and unacceptable. Icon set should either have colors or not, not random mix.

Overall, I don't see that icon set has anything to offer. It's just a collection of logos taken from various websites, scaled down to 48x48 in what I suspect was Adobe Illustrator (which produces consistently terrible quality of exported SVGs) and dumped as SVG files. No work was done to clean them up.

There are much better logo sets.

**Comment by jwr12135** [comment]
Thanks for checking it out.

> There are much better logo sets

The main reason I wanted this set was specifically because of the category of logos (home lab). I think there was another you looked at previously (https://github.com/walkxcode/dashboard-icons), but it seems to be even worse, quality-wise. Is there another set of "home-lab" icons you recommend that we could add to Iconify? For the most part, I'm using Simple Icons and Logos, but they just don't contain a lot of icons that I'd like to have. If there's not another set, maybe I could try to work with the author to improve some of the points you made :man_shrugging:.

**Comment by cyberalien** [comment]
Tried it again, but there are just too many broken icons.

Even if icons with text/font are filtered out, next issue is icons contain invalid/missing gradient ids (meaning icons are incomplete with shapes missing). Quality is absolute garbage. Icons are parsed in alphabetical order, parser didn't even get past icons that start with "c".

Unfortunately that's a common theme with many logo sets. Developers just download icons from web, resize them in bad software, dump as SVG files and call it a job done.

I've just added Devicon set, which was pending for a while because I was waiting for develop branch to be merged in master branch (too many bugs in master branch, but fixed in develop). It should appear on website in couple of hours. It contains many of the same icons that Homelab set does, maybe you'll find icons you need there?
