### ISSUE TITLE
Adding Credit Card Payment Flat Icons Collection

### ISSUE THREAD

**Issue by winston0410** [iconify/icon-sets#88]
Hi, is it possible to add this set of svg as iconset https://www.svgrepo.com/collection/credit-card-payment-flat-icons/? What do I need to do other than creating this issue?

**Comment by cyberalien** [comment]
That cannot be added for several reasons:
1. Not open source. Only icon sets with valid open source licenses are allowed.
2. No way to automatically keep up to date. Icons need to be published somewhere, such as Git repo, NPM package or publicly available Figma file. Downloading icons from some website is not acceptable because that makes maintaining icon set impossible.

**Comment by winston0410** [comment]
I see. Thank you
