### ISSUE TITLE
Add bioicons set

### ISSUE THREAD

**Issue by tlambert03** [iconify/icon-sets#98]
First off, thanks for this amazing library and API. 

I'd like to request support for bioicons, a library of free open source icons for science illustrations in biology and chemistry

- repo: https://github.com/duerrsimon/bioicons
- website: https://bioicons.com
- license: the repo itself is MIT, and icons are MIT, CC-0, CC-BY-3, CC-BY-4, CC-BY-SA-3, & CC-BY-SA-4
- icon SVGs: https://github.com/duerrsimon/bioicons/tree/main/static/icons

I would propose a prefix of `bioicons`

If you feel that too many of these are illustrations, and not icons, I would understand that!  and thanks for your consideration

**Comment by cyberalien** [comment]
Sorry, that set is not usable. There are several issues.

The biggest issue is, those are illustrations, not icons. Icons added to sets should be usable in various menus, buttons and so on. They should be usable at small size, such as 20-24px. Those illustrations aren't usable at small sizes.

Another issue is mix of licenses and various sources. That is not an illustrations set, but collection of various illustration sets or just illustrations taken from other sources. That also makes it unsuitable because of structure: each icon set in Iconify has a clear license, not multiple licenses per icon. Though it can be split to multiple sets, most of them are still unusable because there are just too few images per set.

Then content. Many illustrations contain text that relies on external fonts, which is unacceptable. Icons that contain text are rendered differently in different environments, depending on what fonts are available. In Iconify sets icons must look identical regardless of viewer's environment.

**Comment by tlambert03** [comment]
No worries, thanks for your time!
